### ISSUE TITLE
Search through plugin folders for cosmetics like MoreSuits

### ISSUE THREAD

**Issue by queeek180** [notnotnotswipez/MoreCompany#10]
This would allow custom cosmetics to be more easily uploaded & shared through the Thunderstore. MoreSuits currently does this and as a result there is a fairly large variety of different suits populating the Thunderstore.
[This appears to be how it is done in MoreSuits](https://github.com/x753/Lethal-Company-More-Suits/blob/main/MoreSuits.cs#L59)

**Comment by queeek180** [comment]
Based on how it is done in MoreSuits, I assume replacing line 54 of MainClass.cs with something like his might work:
`public static string dynamicCosmeticsPath = Directory.GetDirectories(Paths.PluginPath, "MoreCompanyCosmetics", SearchOption.AllDirectories);`
I am not familiar with CSharp and was not able to set up a build environment compatible with this repository so I have not been able to test. 

To clarify a little: uploading a .zip folder to Thunderstore containing a BepInEx/plugins/MoreCompanyCosmetics directory would result in the MoreCompanyCosmetics folder being placed into TeamName-ModName/MoreCompanyCosmetics. This project could make use of this to retain non-Thunderstore custom cosmetic support while also making it much easier for cosmetic distribution over Thunderstore, in the same way MoreSuits does.

**Comment by notnotnotswipez** [comment]
Yeah I’m aware of the R2 incompatibility. The next patch addresses this issue by loading all .cosmetics files recursively in the plugins folder. (Folder name for identification is unnecessary as the file extension is specific to MoreCompany)

**Comment by notnotnotswipez** [comment]
Fixed with 1.7.2
