### ISSUE TITLE
Audio error

### ISSUE THREAD

**Issue by David52PG** [notnotnotswipez/MoreCompany#108]
Sometimes, when playing with 5 people, the last person to join the lobby can't hear the host.
this are my mods:
![image](https://github.com/user-attachments/assets/2295126c-1e5c-4bda-b8ca-d857e70b4d7e)
![image](https://github.com/user-attachments/assets/f73748a1-a900-4c36-bfb6-897956691a0e)

**Comment by 1A3Dev** [comment]
This is a vanilla issue, it usually fixes itself if the person rejoins the lobby
