### ISSUE TITLE
Cannot join the lobby when in LAN mode

### ISSUE THREAD

**Issue by CoolLKKPS** [notnotnotswipez/MoreCompany#11]
same as topic

**Comment by taffyko** [comment]
bumping this issue, support for LAN mode would be appreciated
— as a developer, fixing MoreCompany-specific bugs/incompatibilities is nearly impossible when i can't spin up several clients in LAN mode to test with

**Comment by KweezyCode** [comment]
bump

**Comment by 1A3Dev** [comment]
Fixed in v1.8.0+

**Comment by CoolLKKPS** [comment]
hang on

**Comment by 1A3Dev** [comment]
@CoolLKKPS The only thing that mod has that MoreCompany doesn't for LAN is custom usernames and the option to choose the port.

Having two mods that add a custom popup to the join button is always going to conflict with each other for example you probably won't see the option to specify the max player count.

**Comment by CoolLKKPS** [comment]
> The only thing that mod has that MoreCompany doesn't for LAN is custom usernames and the option to choose the port.
> Having two mods that add a custom popup to the join button is always going to conflict with each other for example you probably won't see the option to specify the max player count.

i just thinking if we make a LC server just like Minecraft server, we can have over 100+ people in the same server, the problem is tools (or mods), they just conflict each other and so hard to do it
back to the question, recently MoreCompany add LAN support, but if i have LCDirectLAN, it just override the MoreCompany UI, since MoreCompany only provide IP address option to connect, so i don't think that's enough, override the MoreCompany UI LAN UI should be fine

**Comment by CoolLKKPS** [comment]
i don't think i have to imagine that, Among Us can also do 100+ people lobby. everything can happen, ok still, i don't have enough resource to create a real custom server, but i believe one day it should be can happen

**Comment by CoolLKKPS** [comment]
but for now, this issue should be fixed, so i will close this issue
