### ISSUE TITLE
u said u fixed cosmetics not appearing, but now cosmetics are disappeared after the newest update

### ISSUE THREAD

**Issue by CoolLKKPS** [notnotnotswipez/MoreCompany#110]
later i will provide modpack link to let u test
and same as topic, a bit mad bc i need more time to fix my modpack now :(

**Comment by 1A3Dev** [comment]
If you have either ModelReplacementAPI or TooManyEmotes disable them for now since they both need updating for the new version (the devs of them are aware)

**Comment by ESKape-Key** [comment]
They still don't show up even with just these mods in v66:
![image](https://github.com/user-attachments/assets/11c631d8-e681-430f-9e9a-b68431613cea)

I'm using third person so I can check if the cosmetics are visible. I CAN choose them normally, they just don't show up ingame.

**Comment by 1A3Dev** [comment]
LCThirdPerson doesn't have support for MoreCompany cosmetics

**Comment by CoolLKKPS** [comment]
> If you have either ModelReplacementAPI or TooManyEmotes disable them for now since they both need updating for the new version (the devs of them are aware)

i did installed `TooManyEmotes`, im still updating my modpack for halloween, and the update did break something
i won't update `MoreCompany` for now until other regular active mods support this update, i don't believe they will update their mods real quick rn

**Comment by 1A3Dev** [comment]
> i won't update `MoreCompany` for now until other regular active mods support this update, i don't believe they will update their mods real quick rn

Most mods are already updated for the new version now, the only one that still isn't is ModelReplacementAPI
