### ISSUE TITLE
Cosmetics look detached from playing players POV - Head/face cosmetics blocking view

### ISSUE THREAD

**Issue by QSpukee** [notnotnotswipez/MoreCompany#112]
Took the update for the MoreCompany - the modpack being used has not had any changed other than the update. Since then, any facial  or head cosmetics can be seen through the POV of the player, blocking the ability to see. The body cosmetics can also be seen as if they're completly detached from the player.
![LC_cosmeticBug_SS1](https://github.com/user-attachments/assets/50d2b5ae-a70f-47c1-8cba-06e91bee19aa)
![LC_cosmeticBug_SS2](https://github.com/user-attachments/assets/068674b1-8b42-4ede-b23a-7e3b1b340b98)
![LC_cosmeticBug_SS3](https://github.com/user-attachments/assets/0183b08e-6b3e-4e0c-9132-c7c61285c5f8)
![LC_cosmeticBug_SS4](https://github.com/user-attachments/assets/1e7ed724-fa93-4dac-9ad3-f6d985d18bb4)

**Comment by QSpukee** [comment]
I rolled back to the previous version and the issue went away so it's absolutely a bug in the latest update

**Comment by 1A3Dev** [comment]
> I rolled back to the previous version and the issue went away so it's absolutely a bug in the latest update

This is due to ModelReplacementAPI not being updated for the new version yet

**Comment by grimlament** [comment]
> > I rolled back to the previous version and the issue went away so it's absolutely a bug in the latest update
> 
> This is due to ModelReplacementAPI not being updated for the new version yet so instead of reverting version I'd suggest disabling MRAPI for now (since most mods are updated for the current MoreCompany version already)

How does one disable the MRAPI?

**Comment by 1A3Dev** [comment]
MRAPI is the shortened name of the ModelReplacementAPI mod so you'd just disable that mod

**Comment by grimlament** [comment]
My bad. Just got off of work and have a foggy brain. Thank you.

**Comment by QSpukee** [comment]
I noticed there was an update for MRA - I'll give it a test in the morning and close the bug if all is good

**Comment by QSpukee** [comment]
Issue still exsists - left a comment on the bug opened with the MRA dev

**Comment by QSpukee** [comment]
Issue resolved with lastest MRA update - Version 2.4.12
I needed to download the zip and put the contents into the plugin folder, it's not compatible with thunderstore yet but confirmed it works ✨

Closing~
