### ISSUE TITLE
[Conflict/Issue] a commit evidence shows the detail of conflict with MRAPI, when player disconnected the player model will not destroy

### ISSUE THREAD

**Issue by CoolLKKPS** [notnotnotswipez/MoreCompany#115]
some part of this commit[`1b4bbd5`](https://github.com/1A3Dev/MoreCompany/commit/1b4bbd5e52e45d1542b2bd78ab122f5659d426c5#diff-dbe2dbb6c9e48cc821a810cb0c0bba5117f15ec953c9404b52aa166aa66ed782R492) can break `MRAPI` to destroy the player model when player disconnected, this evidence is found by [V2rtua1](https://thunderstore.io/c/lethal-company/p/V2rtua1), so if im not wrong, `MRAPI` doesn't notice this change that `MoreCompany` already publicized that patch
and tbh i know both side can easily fix this but for some reason the patch are already delayed for too long, so idk, i do perfer this bc MRAPI doesn't know or accidentally ignored this part, im sure someone ahead of me are report this issue in discord already, but i truthly don't know what happen that can takes so long.

**Comment by CoolLKKPS** [comment]
@BunyaPineTree i really do perfer u accidentally ignored this part, sorry for mention u again, u already have the issue ticket in ur repository
@1A3Dev if i was right, this just bc a patch that publicized, i know im might should not mention u (bc that really dumb just bc this), but just in case

**Comment by CoolLKKPS** [comment]
@BunyaPineTree i really do perfer u accidentally ignored this part, sorry for mention u again, u already have the issue ticket in ur repository
@1A3Dev if i was right, this just bc a patch that publicized, i know im might should not mention u (bc that really dumb just bc this), but just in case something that need ur help

**Comment by 1A3Dev** [comment]
> some part of this commit[`1b4bbd5`](https://github.com/1A3Dev/MoreCompany/commit/1b4bbd5e52e45d1542b2bd78ab122f5659d426c5#diff-dbe2dbb6c9e48cc821a810cb0c0bba5117f15ec953c9404b52aa166aa66ed782R492) can break `MRAPI` to destroy the player model when player disconnected, this evidence is found by [V2rtua1](https://thunderstore.io/c/lethal-company/p/V2rtua1), so if im not wrong, `MRAPI` doesn't notice this change that `MoreCompany` already publicized that patch and tbh i know both side can easily fix this but for some reason the patch are already delayed for too long, so idk, i do perfer this bc MRAPI doesn't know or accidentally ignored this part, im sure someone ahead of me are report this issue in discord already, but i truthly don't know what happen that can takes so long.

Vanilla doesn't destroy models at all and neither does MoreCompany

**Comment by CoolLKKPS** [comment]
>MoreCompany just sets the object as inactive for performance reasons then re-enables it when it's used again

yea that exactly as my friend says, so to fix this, just need `MRAPI` do `RemovePlayerModelReplacement` again when player disconnected, i don't really think that's hard... actually

**Comment by CoolLKKPS** [comment]
@1A3Dev but if i was right, that really doesn't help improve performance for `MRAPI`, bc `MRAPI` always need to destory the model anyway, right? so can u make a config option to disable this for compatibility?

**Comment by CoolLKKPS** [comment]
but bc only happen when user have `MRAPI` install, so the config name should related with `MRAPI`

**Comment by 1A3Dev** [comment]
> @1A3Dev but if i was right, that really doesn't help improve performance for `MRAPI`, bc `MRAPI` always need to destory the model anyway, right? so can u make a config option to disable this for compatibility?

No because that'd cause performance issues, it deactivates the entire player script not the model anyway

**Comment by CoolLKKPS** [comment]
okay, even i d like to know what can be happen

**Comment by CoolLKKPS** [comment]
quote some part of the comment from #116
one thing i agree is this issue is not cause by morecompany, bc MRAPI should not only destroy the model on player dc or change suit, that will cause invisible body or invisible masked enemy (mirage mod), even invisible player

**Comment by CoolLKKPS** [comment]
@1A3Dev uh... so follow MIT license i can modify the mod to make my modpack functional, if im right... so i just need to change that `true` to `false`
but btw, even i didn't change anything, DissonanceVoice error will still appear when player dc

**Comment by 1A3Dev** [comment]
> so i just need to change that `true` to `false`

I'm confused what `true` you are referring to? If you are trying to say you want to remove the code that disables the player controller then I wouldn't suggest that as it's necessary for performance reasons, if all the inactive player controllers are left active then it has a large hit on FPS

**Comment by CoolLKKPS** [comment]
i did wonder how, i already know framerate drop will happen when returning to orbit, but that cannot convince me to not doing that

**Comment by CoolLKKPS** [comment]
i do believe this issue is not cause by MC, but shoule be not impact too much so i doing this anyway

**Comment by notnotnotswipez** [comment]
You underestimate how important that optimization is when having more than about 15 inactive players. Keep in mind, the higher your lobby playercount is, the higher your inactive player count is, and if they aren't disabled then they will still run operations every frame.

**Comment by CoolLKKPS** [comment]
>You underestimate how important that optimization is when having more than about 15 inactive players. Keep in mind, the higher your lobby playercount is, the higher your inactive player count is, and if they aren't disabled then they will still run operations every frame.

got it
