### ISSUE TITLE
will always trigger `Refreshing voice playback objects.` info log when something happen, cause framerate drop

### ISSUE THREAD

**Issue by CoolLKKPS** [notnotnotswipez/MoreCompany#116]
@1A3Dev 
[Info   : Unity Log] Refreshing voice playback objects. Number of voice objects found: 10

**Comment by 1A3Dev** [comment]
That's not a log from MoreCompany, that's vanilla

**Comment by CoolLKKPS** [comment]
i know, uh so in previous, i need morecompany can compatible with MRAPI in order to help build the modpack for another modpack author, so i have to modify the dll by using dnspy
one thing i agree is #115 issue is not cause by morecompany, bc MRAPI should not only destroy the model on player dc or change suit, that will cause invisible body or invisible masked enemy (mirage mod), even invisible player
ok that's the background

i deleted `OnPlayerDC` line in `TogglePlayerObjectsPatch`, but after that this issue trigged, idk what happen, that's the reason in here to ask
