### ISSUE TITLE
The Cosmetic Model does not appear, but the icon does

### ISSUE THREAD

**Issue by DHStyle541** [notnotnotswipez/MoreCompany#15]
Hi, I want to ask
Why doesn't the Cosmetic Model that I created appear, only the icon appears?

https://github.com/notnotnotswipez/MoreCompany/assets/154591650/956dc137-9a84-4581-aab4-392d752c0647

and is this normal when just starting out?
![gambar](https://github.com/notnotnotswipez/MoreCompany/assets/154591650/db92c2c8-67f4-4281-98e0-11d3399e5a4c)

and can you provide a tutorial on adding cosmetics but in video form, not a wiki.

*I'm a unity newbie so I don't really understand
*I'm using Unity version 2022.3.9f1. according to the Wiki you created

**Comment by notnotnotswipez** [comment]
Project is not HDRP
