### ISSUE TITLE
More company with V47 not working

### ISSUE THREAD

**Issue by Seef25** [notnotnotswipez/MoreCompany#19]
So hey, whenever i load More company version 1.7.2 it will let me host, but whenever someone tries to join me it breaks for some reason and disconnects me too

**Comment by notnotnotswipez** [comment]
Are you on v47 or v45

**Comment by Seef25** [comment]
V47, I mentioned it in the title

**Comment by notnotnotswipez** [comment]
Oh I’m blind, sorry. MoreCompany does not work with the beta branch of the game. It will not be targeting betas

**Comment by Seef25** [comment]
Oh alright, thanks for letting me know
