### ISSUE TITLE
Fails when joining by freezing with "ghost" player present.

### ISSUE THREAD

**Issue by jr1221** [notnotnotswipez/MoreCompany#25]
Hi, 
For me and only me (of 15 plus people I know using more company) I can't initialize into the game. I join and get situation where the screen is foggy and I cannot move, and the game eventually crashes.  I can be seen by others, just I cannot interact at all with the game.  This was reproducible without any other mods but mine.  I CAN host 100% fine.

Here is the error message.  I did a clean reinstall of windows and the error still occured.  I feel like something is being carried over via steam on the cloud, idk I'm just guessing. Thanks in advance for any advice you can give.

Windows 11
Thunderstorm Mod Manager with MoreCompany v1.7.2 and v45 game for all players.

![image](https://github.com/notnotnotswipez/MoreCompany/assets/53871299/34738570-6924-4b53-8cfa-f3a53fd678e2)

**Comment by jr1221** [comment]
The issue is probably somewhere in the below class.  Based on this it seems like my client cannot handle a message being received?  Perhaps related to cosmetics?  Any help is much appreciated.

https://github.com/notnotnotswipez/MoreCompany/blob/466459d790fbc9afcaa83ddce3189670c7621b87/MoreCompany/ChatPatches.cs#L97C8-L97C8

**Comment by 1A3Dev** [comment]
> Here is the error message. I did a clean reinstall of windows and the error still occurred. @jr1221 

The error you showed is most likely completely unrelated to your issue since I had it and was able to host/join lobbies completely fine (unless you're having a conflict with another mod or something similar). That error has been fixed in https://github.com/notnotnotswipez/MoreCompany/issues/49 anyway so should be fixed in the next update.

**Comment by jr1221** [comment]
Thanks!
