### ISSUE TITLE
Mod not working with game's latest version 49 

### ISSUE THREAD

**Issue by Android2771** [notnotnotswipez/MoreCompany#30]
More than four players are not allowed to join with the mod as of now. Could you perhaps update the mod? :)

**Comment by SKAREZ** [comment]
I guess not, MC will not be updated for beta branches until they go stable releases
- [See this message from notnotnotswipez](https://github.com/notnotnotswipez/MoreCompany/issues/19#issuecomment-1872350702)
  > "MoreCompany does not work with the beta branch of the game. It will not be targeting betas"

**Comment by notnotnotswipez** [comment]
It does function on v49, make sure everyone has the mod installed

**Comment by Android2771** [comment]
It works now, thanks :)
