### ISSUE TITLE
Keep getting an error that only allows me to add one cosmetic

### ISSUE THREAD

**Issue by DrMikeSmith** [notnotnotswipez/MoreCompany#32]
I've been trying to add some custom cosmetics and I'm probably just really stupid but it's not working and I have spent 8 hours trying to fix it. Please help me understand the issue

Log:
[LogOutput.log](https://github.com/notnotnotswipez/MoreCompany/files/13919463/LogOutput.log)

The Error that keep appearing:
[Error  :MoreCompany] Duplicate cosmetic id: replace.me

Pictures:
![Capture](https://github.com/notnotnotswipez/MoreCompany/assets/156437177/79f09d74-5524-449f-9074-6c9eacf788e0)
![Capture2](https://github.com/notnotnotswipez/MoreCompany/assets/156437177/d6994c13-fb84-4bad-87a5-d6be64402143)

**Comment by DrMikeSmith** [comment]
The icon also isn't working

**Comment by notnotnotswipez** [comment]
You aren’t changing the identifier in unity when you’re making the cosmetic. You are supposed to replace “replace.me” with something unique like “author.cosmeticname”

**Comment by notnotnotswipez** [comment]
You also are not setting the icon as thats the default icon. Make sure you’re applying your changes to the prefab and not just the gameobject in the scene

**Comment by DrMikeSmith** [comment]
I am the biggest moron that has ever lived. 
I was adding the variables to the model itself instead of the anchor point.
