### ISSUE TITLE
[Compatibility] Reflection invoke causes issues

### ISSUE THREAD

**Issue by Edouard127** [notnotnotswipez/MoreCompany#33]
The spectate next function here https://github.com/notnotnotswipez/MoreCompany/blob/master/MoreCompany/SpectatePatches.cs calls the original RaycastSpectateCameraAroundPivot instead of the patches functions (I think ?)

So correct me if I'm wrong, I think it would be better to call the instance function instead of invoking using reflections

**Comment by notnotnotswipez** [comment]
- RaycastSpectateCameraAroundPivot is a private function, some form of reflection is needed to call the function. ReflectionUtils calls it on the instance.
- The patch cannot just call the original function that its patching into, that would remove the purpose of the overwrite
