### ISSUE TITLE
Making custom cosmetics seems to be broken

### ISSUE THREAD

**Issue by mikegoutokujiii** [notnotnotswipez/MoreCompany#35]
I'm trying to make a few custom cosmetics, but no matter what I do, every time they're built and tested in-game, they do not show up on the model. Not on the preview, not in a lobby, absolutely nowhere in-game.
I'm wondering if something to do with building them is broken, or maybe I'm just doing something wrong, but as far as I know, I've followed everything on the guide *extremely* carefully as to avoid any potential problems. Before you say "did you move the parts that said (DO NOT MOVE)?", No, I did not. I left them exactly where they were. Here's two images showing where it is in Unity, but how it isn't anywhere in-game:
![Screenshot 2024-01-13 192021](https://github.com/notnotnotswipez/MoreCompany/assets/110744461/b0abaf5a-308d-493f-b113-8999e3f05bdc)
![Screenshot 2024-01-13 192320](https://github.com/notnotnotswipez/MoreCompany/assets/110744461/eab2040f-59cd-41a8-83e0-3358f47737f6)
I'd appreciate any sort of help here... this is really starting to get annoying. X_X

**Comment by JademusSreg** [comment]
I have also encountered this issue. The project must be configured to use the High Definition Render Pipeline. [Here are instructions from Unity](https://unity.com/how-to/getting-started-high-definition-render-pipeline-hdrp-games).

@notnotnotswipez I recommend linking to a template HDRP project to reduce the number of these issues reported.

**Comment by notnotnotswipez** [comment]
The cosmetic guide specifies to make an HDRP project, if people miss that then they’d miss the link anyway

**Comment by JademusSreg** [comment]
Or perhaps a link to the above instructions? 😉
