### ISSUE TITLE
Players keep getting added to `radarTargets` if a radar booster was active when `SendNewPlayerValuesClientRpc` was called.

### ISSUE THREAD

**Issue by Charlese2** [notnotnotswipez/MoreCompany#45]
When `SendNewPlayerValuesClientRpc` is called, if the count of `radarTargets` doesn't match the count of player controllers it will just keep adding them as radar targets. If the count doesn't match one time that `SendNewPlayerValuesClientRpc` is called it will always not match as it keeps adding radar targets.
https://github.com/notnotnotswipez/MoreCompany/blob/086366e0f35b7d1f7e33c8bff07de8af947e4dec/MoreCompany/MainClass.cs#L319
Radar Boosters also count as radar targets when they are active, but they have `isNonPlayer` set to `true` under the type `TransformAndName`.
Late join mods or malicious clients can cause `SendNewPlayerValuesClientRpc` to be called while a radar booster is active.

**Comment by notnotnotswipez** [comment]
Fixed with #50
