### ISSUE TITLE
[Conflict] cosmetics will blocked by some anti-cheat mods

### ISSUE THREAD

**Issue by CoolLKKPS** [notnotnotswipez/MoreCompany#73]
same as topic

**Comment by Flloppis** [comment]
Amma havin' this problem aswell- 
Me friend who hostsii lobby has set theirra configs ta Show Cosmetics=True anda Default Cosmetics=True
![image](https://github.com/notnotnotswipez/MoreCompany/assets/157853816/c03e9403-9c0c-4a09-ae1e-fdd8c7ed55a2)
We havva no idea wha issa causin' it..

**Comment by CoolLKKPS** [comment]
should be fixed but will do more deeper test, after that i will close this issue

**Comment by CoolLKKPS** [comment]
@notnotnotswipez @1A3Dev

**Comment by 1A3Dev** [comment]
Could you send your mod profile code? Since I've not seen anyone else report any issues with it.

**Comment by CoolLKKPS** [comment]
@1A3Dev so this issue happen bc conflict with some anti-cheat mods (not only 1)

**Comment by CoolLKKPS** [comment]
if i was correct, this conflict with HostFixes v1.0.14 by CharlesE2, and AntiCheat v0.6.3 by chuxiaaaa, will change the title

**Comment by CoolLKKPS** [comment]
some code from AntiCheat made by chuxiaaaa are commit by HostFixes author CharlesE2, so yea will notify both authors

**Comment by CoolLKKPS** [comment]
and yes i can't take the risk to disable anticheat just for some cosmetics, if i really have to choose one

**Comment by CoolLKKPS** [comment]
fixed
