### ISSUE TITLE
Custom Hat not showing up in-game (v45)

### ISSUE THREAD

**Issue by Bunpt** [notnotnotswipez/MoreCompany#9]
I made this model to use with my friends and have been following the tutorial exactly, but my model still isn't showing up in-game
![image](https://github.com/notnotnotswipez/MoreCompany/assets/153488057/63a7c072-d930-409c-8002-3d21fe61347b)
![image](https://github.com/notnotnotswipez/MoreCompany/assets/153488057/16100ee2-8445-43b0-99c3-f88641004465)
![image](https://github.com/notnotnotswipez/MoreCompany/assets/153488057/04ae8898-808c-4568-b6b9-8518b6cb5473)
I've tried having the model be a .blend, .fbx and .obj file but neither have worked. I've also tried unpackaging the fbx/obj while it was in the scene and then repackaging as instructed but that still didnt work.
![image](https://github.com/notnotnotswipez/MoreCompany/assets/153488057/c39b1a8f-5818-4ff6-8611-c28a60e56a53)
I've also tried things that weren't instructed like dragging the cosmetic instance script into the bundle (probably required but not mentioned on the tutorial), replacing the HatCosmetic with the unpackaged fbx, and everything I could think of to no avail.

I'm only making this because I have genuinely no idea what's causing this or how to fix it in the hopes that you're able to help or see something I'm not.

**Comment by F2PShadowek** [comment]
I have the same problem ://

**Comment by notnotnotswipez** [comment]
Your project is not HDRP, its also why the guy is pink

**Comment by Bunpt** [comment]
> Your project is not HDRP, its also why the guy is pink
![image](https://github.com/notnotnotswipez/MoreCompany/assets/153488057/02923418-31be-45ef-b09b-333aaea06440)
Yep, that did it! Thanks for the reply!
